export default {
  badge: "Badge",
  button: "Button",
  card: "Card",
  checkbox: "Checkbox",
  input: "Input",
  "kpi-card": "KPICard",
  select: "Select",
  tabs: "Tabs",
  avatar: "Avatar",
  tooltip: "Tooltip",
  dialog: "Dialog",
  "dropdown-menu": "DropdownMenu",
  progress: "Progress",
  skeleton: "Skeleton",
  table: "Table",
  "theme-toggle": "ThemeToggle",
  "command-menu": "CommandMenu",
  "app-shell": "AppShell",
  "area-chart": "AreaChart",
  icons: "Icons",
};
